# coding: utf-8

"""
    Universal Worker Service (UWS)

    The Universal Worker Service (UWS) pattern defines how to manage asynchronous execution of jobs on a service.

    The version of the OpenAPI document: 1.2
    Contact: grid@ivoa.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import re  # noqa: F401
from typing import Any, ClassVar, Optional

from pydantic import BaseModel

from openapi_server.models.parameter import Parameter


class Parameters(BaseModel):
    """
    Parameters
    """  # noqa: E501

    parameter: Optional[list[Parameter]] = None
    __properties: ClassVar[list[str]] = ["parameter"]

