# coding: utf-8

"""
    Universal Worker Service (UWS)

    The Universal Worker Service (UWS) pattern defines how to manage asynchronous execution of jobs on a service.

    The version of the OpenAPI document: 1.2
    Contact: grid@ivoa.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import openapi_server.models.error_responses
from fastapi import FastAPI
from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Universal Worker Service (UWS)",
    description="The Universal Worker Service (UWS) pattern defines how to manage asynchronous execution of jobs on a service.",
    version="1.2",
)

app.include_router(DefaultApiRouter)
app.add_exception_handler(Exception, openapi_server.models.error_responses.http_exception_handler)
